services:
  - type: web
    name: fitcode-gym-backend
    env: python
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "python src/main.py"
    plan: free
