services:
  - type: web
    name: fitcode-gym-backend
    env: python
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT src.main:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: DATABASE_URL
        value: "postgresql://postgres.qqjpphojzkpastodgpfr:sanket242104@aws-0-ap-south-1.pooler.supabase.com:5432/postgres"
      - key: SECRET_KEY
        value: "your-secret-key-here"
      - key: QR_ENCRYPTION_KEY
        value: "LF8iwbnz4hm8zDSqx9T--F0Rdtf-ZMzKANGzu50iXl4="
      - key: FLASK_ENV
        value: "production"
